import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author XII
 */
public class BILL extends javax.swing.JFrame {

    /**
     * Creates new form BILL
     */
   
    


    
    

    
    
    public BILL() {
        initComponents();
        
        try
{
    int billno=0;
       Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/inox","root" , "tiger");
          Statement stmt = con.createStatement();
         String sql="select billno from bill;";
 
            ResultSet rs=stmt.executeQuery(sql);
            
            
            while(rs.next())
            {
            billno=rs.getInt(1);
            }
            billno=billno+1;
            jLabel5.setText(""+billno);
}catch(Exception e)
{


}
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 50, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(164, 30, 108, 20);

        jLabel2.setText("CONTACT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 70, 70, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(164, 68, 108, 20);

        jLabel3.setText("ADDRESS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(86, 99, 60, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(164, 99, 166, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "screen", "bookingdate", "time", "moviename", "seats"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(51, 218, 409, 157);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(147, 177, 90, 23);

        jLabel4.setText("BILL NO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 10, 60, 14);

        jLabel5.setText("1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(169, 10, 46, 14);

        jButton2.setText("CONFIRM BOOKING");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(176, 428, 170, 23);

        jLabel6.setText("total cost");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 390, 70, 14);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(214, 390, 60, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TO SHOW in TaBle
 DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        
        int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
    dm.removeRow(i);
}
        
        
        try{
           
    Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/inox","root" , "tiger");
          Statement stmt = con.createStatement();
         String sql="select * from seat;";
        
        ResultSet rs=stmt.executeQuery(sql);
        String s1,s2,s3,s4,s5,jmoviename=null;
        int noofseats=0;
      while(rs.next())
      {
          s1=rs.getString(1);
          s2=rs.getString(2);
          s3=rs.getString(3);
          s4=rs.getString(4);
          s5=rs.getString(5);
          jmoviename=rs.getString(4);
          dm.addRow( new Object[] { s1,s2, s3, s4,s5});
         noofseats++;
      }
  // PRICE
             sql="select PRICE from newmovie where moviename='"+jmoviename+"';";
           rs=stmt.executeQuery(sql);
           int totalcost=0;
              if(rs.next())
              {
              totalcost=noofseats*rs.getInt(1);
              
              jLabel7.setText(""+totalcost);
              }
              
              
              
    }                                    
    catch(Exception e) { 
        JOptionPane.showMessageDialog(rootPane,e);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try
{
int billno=Integer.parseInt(jLabel5.getText());
 String name=jTextField1.getText();
 int contact=Integer.parseInt(jTextField2.getText());
 String address=jTextArea1.getText();
 int totalcost=Integer.parseInt(jLabel7.getText());
DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
  int rows = tb.getRowCount();
       for(int i =0; i<rows; i++)
        {
            
        String screen = tb.getValueAt(i,0)+"";
         String bkdate = (String) tb.getValueAt(i,1);
          String time = (String) tb.getValueAt(i,2);
          String mname = (String) tb.getValueAt(i,3);
          String seats = (String) tb.getValueAt(i,4);
        try{
            Class.forName("java.sql.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost/inox","root","tiger");
            String sql = "insert into bill values("+billno+",'"+name+"',"+contact+",'"+address+"','"+screen+"','"+bkdate+"','"+time+"','"+mname+"','"+seats+"',"+totalcost+");";
            Statement stmt = Con.createStatement();
            stmt.executeUpdate(sql);
           
        } catch(Exception k){
            JOptionPane.showMessageDialog(null,k);
        }
            JOptionPane.showMessageDialog(null,"record saved");
        }
    // seats remove
        try{
            Class.forName("java.sql.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost/inox","root","tiger");
            String sql = "delete from seat;";
            Statement stmt = Con.createStatement();
            stmt.executeUpdate(sql);
           
        } catch(Exception k){
            JOptionPane.showMessageDialog(null,k);
        }
     
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}  
        
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
