import java.sql.*;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/**
 *
 * @author XII
 */
public class NEWMOVIE extends javax.swing.JFrame {

    /**
     * Creates new form NEWMOVIE
     */
    public NEWMOVIE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("MOVIE NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(91, 29, 80, 14);

        jLabel2.setText("CENSOR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(94, 55, 60, 14);

        jLabel3.setText("RELEASING DATE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 81, 110, 14);

        jLabel4.setText("REMOVING DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(72, 112, 100, 14);

        jLabel5.setText("PRICE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(89, 139, 50, 14);

        jLabel6.setText("TIME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(89, 174, 40, 14);

        jLabel7.setText("SCREEN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(89, 276, 70, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(195, 26, 115, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "U", "U/A", "A", "S" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(195, 52, 115, 20);

        jTextField2.setText("2019-10-08");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(195, 78, 115, 20);

        jTextField3.setText("2019-11-06");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(195, 109, 115, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(195, 136, 115, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SCREEN 1", "SCREEN 2", "SCREEN 3" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(195, 270, 115, 20);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(72, 322, 80, 23);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(204, 322, 55, 23);

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(323, 322, 100, 23);

        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(195, 171, 115, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{
 String name=jTextField1.getText();
   String censor=(String)jComboBox1.getSelectedItem();
    String date1=jTextField2.getText();
     String date2=jTextField3.getText();
   int price=Integer.parseInt(jTextField4.getText());
   String time=jTextField5.getText();
   String screen=(String)jComboBox2.getSelectedItem();
 
     Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/inox","root","tiger");
    String sql="insert into newmovie values('"+name+"','"+censor+"','"+date1+"','"+date2+"',"+price+",'"+time+"','"+screen+"');";
    Statement stmt=con.createStatement();
    stmt.executeUpdate(sql);
    JOptionPane.showMessageDialog(null,"Record saved successfully");
    
    
    
     
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}  
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jTextField1.setText(null);
jTextField2.setText(null);
jTextField3.setText(null);
jTextField4.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEWMOVIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEWMOVIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEWMOVIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEWMOVIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEWMOVIE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
